name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: API_TOKEN

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create config.js from GitHub Secret
        run: |
          echo "const API_TOKEN = '${{ secrets.API_TOKEN_KEY }}';" > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
